parameters:
  app.collections:
    - col1vkehesfftd7j9ae7ufaq42rtry69hckm00tf70tc527jkq42qw6sk0pxpy
    - col1fnzpxnhr365z9d5phxc0a9nya3ypn5t8je4de97j3pux2anl64uqv0m0gs

  app.profiles:
    - 19bd6b5cbbbc7571222fea5f7a7c74eb045ffc5db0903ae039f07bf1a9c211ec

  app.homeContent:
    logo: https://assets.mainnet.mintgarden.io/thumbnails/34f03d6d638d7a88ee4ef22241a65cf4fbad6a9cc9273bb18927cfba95d46ead_512.png
    motto: 'we <3 chia!'
    title: Chia Friends
    subtitle: 10,000 eco-bit NFTs on Chia, from Chia.
    description: Display your Chia Friend PFP on Twitter and more to help spread the news about building projects on our new NFT standard. There’s also a puzzle embedded in the collection for the community to discover…that’s your only hint for now!
    aboutTitle: Chia Friends
    aboutImage: https://assets.mainnet.mintgarden.io/thumbnails/34f03d6d638d7a88ee4ef22241a65cf4fbad6a9cc9273bb18927cfba95d46ead_512.png
    aboutContent: |
      Display your Chia Friend PFP on Twitter and more to help spread the news about building projects on our new NFT standard. There’s also a puzzle embedded in the collection for the community to discover…that’s your only hint for now!
      
      This description also supports line breaks.
    twitterLink: https://twitter.com/chia_friends
    discordLink: https://discord.com/invite/ECAteZ2B6n
    highlightNfts:
      [
        https://assets.mainnet.mintgarden.io/thumbnails/e49938a641b71a3dead9d309a6f96a6f502b68d2096b4318d7b9a21d0d77633a.png,
        https://assets.mainnet.mintgarden.io/thumbnails/a45e755bf2b6bf7cd9dd39394db6a286b789ba5b34fff8395453a1a5f6e5c7d0.webp,
        https://assets.mainnet.mintgarden.io/thumbnails/74c7f4dff57ef1da134bb3e904195e1d6eb33278f9dcb28d1f464665b52cb548.png,
        https://assets.mainnet.mintgarden.io/thumbnails/944b20b91b985fa30c7215cdefbda66cd0ee450eea609de7f0f80b0297a51de2.png,
        https://assets.mainnet.mintgarden.io/thumbnails/3029e6ad8405272e8cd0921e67e0a3d194a1687acbe8881f01d6cf155ef94c72.png,
      ]
